### ISSUE TITLE
Pokemon Sword [21.9 Ultrawide v1.3.2] crashes on launch

### ISSUE THREAD

**Issue by Gmorrk** [Fl4sh9174/Switch-Ultrawide-Mods#92]
Unfortunately neither Pokemon Sword nor Shield seem to work. They crash on boot. I tested both om Ryujinx, using only the newest Update 1.3.2 and both DLCs. No other mods or files. 
(Other games work fine. Also THANK YOU for your hard work.)

**Comment by Fl4sh9174** [comment]
Does it happen on Yuzu/Citron/Sudachi?

**Comment by Gmorrk** [comment]
Sudachi does work. Really weird. Thank you though! :)

**Comment by Fl4sh9174** [comment]
Fixed the ultrawide for both Sword and Shield, working across all Emulators and Switch now, just redownload the desired mod.

**Comment by Yoghurt4C** [comment]
did you push the update? the zips are from a week ago and still crash

**Comment by Fl4sh9174** [comment]
> did you push the update? the zips are from a week ago and still crash

My bad, i forgot to push the update, its fixed now, you can download the fixed version, i tweaked the mod too, its more precise than before, from 2.3750 to 2.38888888 aspect ratio

**Comment by Fl4sh9174** [comment]
> damn. I was going to try and jury rig a 16:10 aspect ratio mod out of this one but now there are more variables and the one magic number got replaced by 2

@enabled
00d93414 CCF9A7F2 // Culling
00607de8 A999D9F2 // Aspect Ratio
00607dec 89F9E7F2 // Aspect Ratio
006076c4 E8FFFF17 // Camera distortion
00607664 A9999952 // Camera distortion
00607668 89F9A772 // Camera distortion
0060766c 17000014 // Camera distortion
@stop

just place it on your current mod for pokemon sword, its tweaked to 16:10. with the best precision of the current mod, and no more crash.
